### ISSUE TITLE
Oh one more thing: K value of mutual inductance seems to be wrong

### ISSUE THREAD

**Issue by CIVITAS-John** [svenboulanger/SpiceSharp#18] opened 2017-12-31 14:32 UTC
Hi Sven,

I've noticed another problem which troubles me a little :) That's the K(MUTcoupling) value of mutual inductance. Right now (using Development branch) it behaves as if MUTcoupling = 0.5 equals to K = 1.0 while MUTcoupling = 1.0 causes unpredictable behavior. I have no ability to investigate it more deeply, and therefore can only submit an issue here.

Thank for your great work again.
Best Regards

**Comment by CIVITAS-John** [comment] 2018-01-01 12:50
Hi.. One more potential bugs:

Connect a circuit with a AC source (sin waveform), a resistor, a capacitor and a inductor in a series and you'll find out that some 'sparse matrix exception' happens. Add a resistor parallel to the capacitor solve this, but the inductor shows zero current which is impossible since the capacitor has. I don't know whether there are any unit tests concerning this and just cannot find one in Development Branch unit tests. 

If needed I can build some codes repeating it; since I am using program to generate circuit it will not give me the C# code at the same time...

**Comment by CIVITAS-John** [comment] 2018-01-01 12:50
Happy New Year :)

**Comment by svenboulanger** [comment] 2018-01-01 22:41
Hello,

The inductor and mutual inductance has not been properly tested. We will add these unit tests soon.
We are working in the refactoring branch right now with some big changes and I can confirm that I found some bugs when using inductors.

Happy new year to you too 😄 
Sven

**Comment by CIVITAS-John** [comment] 2018-01-02 06:46
So can I use Refactoring branch for now? lol

**Comment by svenboulanger** [comment] 2018-01-02 10:56
I believe that will be difficult. The refactoring branch is not ready to be merged with the development branch yet.

**Comment by CIVITAS-John** [comment] 2018-01-02 15:53
Can it pass unit tests? My program is loosely based on Spice# so it won't cost too much.

**Comment by svenboulanger** [comment] 2018-01-02 16:03
It does not pass unit tests because that project also depends (for now) on the SpiceSharp.Parser project.
The ones that I believe I got working right now are: R, L, C, V (independent voltage source) and I (independent current source).

**Comment by CIVITAS-John** [comment] 2018-01-03 12:52
So if I do not use Parser, RLC circuits are behaving correctly in Refactoring branch?

**Comment by svenboulanger** [comment] 2018-02-04 12:35
Unit test has been added for a inductors and mutual inductances.

**Closed by svenboulanger** 2018-02-04 12:35 UTC
Labels: bug
